services:
  440th.flight_management.controller:
    class: 440th\flight_management\controller\main
    arguments:
      - '@config'
      - '@controller.helper'
      - '@language'
      - '@template'
 440th.flight_management.listener:
   class: 440th\flight_management\event\main_listener
   tags:
     - { name: event.listener }