services:
    VFW440.flight_management.controller:
        class: VFW440\flight_management\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'
    VFW440.flight_management.listener:
        class: VFW440\flight_management\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }